#!/usr/bin/env python3

from os import system, chdir, listdir
from os.path import isfile
import re

def main():
    chdir("projects")
    dirs = [f"0{i}" for i in range(1, 6)]
    inner_dirs = ["01", "02"]
    for dir in dirs:
        for inner in inner_dirs:
            chdir(f"{dir}/{inner}")
            for filename in listdir("."):
                file = re.search(".class", filename)
                if file:
                    system(f"rm {filename}")
            chdir("../..")

if __name__ == "__main__":
    main()

